# Deploy Nuxt site to GitHub Pages using Bun
name: Deploy Nuxt site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: nuxt

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            dist
            .nuxt
            node_modules
          key: ${{ runner.os }}-bun-nuxt-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-nuxt-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build static site
        # Nuxt 3 uses `.output/public`, Nuxt 2 uses `dist`
        run: |
          if grep -q '"nuxt": "3' package.json; then
            bun run build
          else
            bun run generate
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Adjust based on your Nuxt version output
          path: |
            ./dist
            ./.output/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
